# Generated by Django 3.0 on 2021-01-16 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlairInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=70)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('password', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=80)),
                ('ssc', models.IntegerField()),
                ('inter', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='image/')),
                ('loc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
