# Generated by Django 3.0 on 2021-01-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('firstname', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='User Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Field')),
                ('dob', models.DateField(verbose_name='Date Of Birth')),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('image', models.ImageField(upload_to='image/')),
                ('ssc', models.IntegerField(verbose_name='SSC Marks')),
                ('inter', models.IntegerField(verbose_name='Inter Marks')),
                ('department', models.CharField(choices=[('H', 'Hr'), ('M', 'Marketing'), ('F', 'Finance'), ('C', 'Cat')], max_length=2)),
                ('is_selected', models.BooleanField(default=True)),
            ],
        ),
    ]
