# Generated by Django 3.0 on 2021-01-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_auto_20210107_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='salary',
            field=models.CharField(max_length=20),
        ),
    ]
