# Generated by Django 3.0 on 2021-01-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0003_auto_20210107_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pm',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
