# Generated by Django 3.0 on 2021-01-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='recipes/%Y/%m/%d')),
                ('description', models.TextField(verbose_name='Description')),
                ('ingredients', models.TextField(verbose_name='Ingredients')),
                ('preparation', models.TextField(verbose_name='Preparation')),
                ('created', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
